### ISSUE TITLE
Какво ще правим?

### ISSUE THREAD

**Issue by dantcho** [TheMightyMidgetsTeam/TheMightyMidgetsProject#1]
Нека тук обсъждаме идеите за проект!

**Comment by PetyoLazarov92** [comment]
Здравей, на мен ми харесва идеята за домова книга,  в интернет има доста
подобни такива , трябва да видим нашта с какво ще се различава от другите,
имам предвид да разгледаме по- използваните и по- известните сайтове за
ръководене на етажна собственост, да ги тестваме и да открием какви
недостатъци имат, било то визия или функционалност, за да създадем нещо
което да се различава и да бъде по-добро.
На 7.08.2016 г. 16:48 "dantcho" notifications@github.com написа:

**Comment by dantcho** [comment]
Да се върнем на моето предложение за колегите които не са го видяли в другата система.

Система за управление на етажна собственост

Виртуална домова книга - база на собствениците и апартаментите (Име, телефон ... , каквото се изисква в домовата книга)

форум или блог в който се разискват проблеми

Ще има потребители с роли
домоуправител - ще може да администрира базата с собствениците на апартаменти
собственик - ще може да редактира само собствената си информация в домовата книга. \Това ще е трудно.
ползвател или наемател - ще може да участва в форума.

Ако остане време може да развием
гласувания , финанси , ....

На долния линк съм подготвил един MindMap

https://www.mindmup.com/#m:a1f897a7c041ff0134cb720a1453db1745

Очаквам коментари!

**Comment by PetyoLazarov92** [comment]
Здравей, Разгледах MindMap и не ми става много ясно какво означава **Застроена част** и **дял от общите части на сградата**, това нещо като притежание на таван , маза и гараж ли е, а ако има такива вписват ли се някъде? Другото за постовете не схващам малко има два пъти **пост** и **пост/баща**. Иначе си се постарал доста и е добре структурирано.

**Comment by dantcho** [comment]
Решено е! Правим сайт с обяви за работа.
В папката SiteView ще блъскаме всички файлове относно визията и функционалността
