### ISSUE TITLE
Среща!

### ISSUE THREAD

**Issue by dantcho** [TheMightyMidgetsTeam/TheMightyMidgetsProject#2]
на 13.08.2016 - събота от 11:00ч. организираме среща в сградата на Софтуни.

**Comment by PetyoLazarov92** [comment]
Предлагам и да си направим някакво разпределение, кой с какво ще се занимава. Аз нямам възможност да дойда на срещата, ако има някакъв друг начин да се свържем помежду си, по скайп или по телефон да се чуем в реално време, ще се радвам.

**Comment by dantcho** [comment]
на срещата се разбрахме да подготвя скелета до неделя и после почвате :)
